name: tests

on:
  push:
  pull_request:

jobs:
  janet-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Janet
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git
          git clone --depth 1 --branch v1.40.1 https://github.com/janet-lang/janet.git
          cd janet
          make
          sudo make install
      - name: Run tests
        run: janet test/main-test.janet
