name: tests

on:
  push:
  pull_request:

jobs:
  janet-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Janet
        run: |
          sudo apt-get update
          sudo apt-get install -y janet
      - name: Run tests
        run: janet test/main-test.janet
